[tool.poetry]
name = "problemsolver"
version = "0.1.0"
description = "Nonlinear problem-solving algorithms"
authors = ["emunsing <eric.munsing@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"
attrs = "*"
pytest = "*"
numpy = "*"
matplotlib = {version = "*", extras = []}
pandas = {version = "*", extras = ["performance"]}
click = "*"
openai = "*"
langchain = {version = "*", extras = ["openai"]}
langchain-openai = "*"
optuna = "*"

[tool.poetry.group.torch]
optional = true
[tool.poetry.group.torch.dependencies]
torch = "*"
torchvision = "*"

[tool.poetry.group.analytics]
optional = true
[tool.poetry.group.analytics.dependencies]
plotly = "*"
jupyter = "*"
ipykernel = "*"
seaborn = "*"
matplotlib = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
